const ComplaintData = [
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "whine joy",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Pending",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
	{
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "tester nom",
		date: "Today — April 22, 2022",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Pending",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
	},
];
export default ComplaintData;
