const ComplaintData = [
	{
		id: "12iveynv89yf9n9vnwin21nn",
		grievanceId: "12iveynv89yf9n9vnwin21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Stewart",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioinvrv9nhnwv821nn",
		grievanceId: "12ioinvrv9nhnwv821nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-13",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Stewart",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioiirwenj98vr9wnw81nn",
		grievanceId: "12ioiirwenj98vr9wnw81nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Stewart",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioiirwen9wr8u9rnv1nn",
		grievanceId: "12ioiirwen9wr8u9rnv1nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Stewart",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioiruewny8nrwe8y8n8wr1nn",
		grievanceId: "12ioiruewny8nrwe8y8n8wr1nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Stewart",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12io9re8un98vr9n8ryw21nn",
		grievanceId: "12io9re8un98vr9n8ryw21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioire8nu9wrnrn9821nn",
		grievanceId: "12ioire8nu9wrnrn9821nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1r98un9u8wn9hrn91nn",
		grievanceId: "12ioi1r98un9u8wn9hrn91nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12i9rmu8nwr99rvn21nn",
		grievanceId: "12i9rmu8nwr99rvn21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1rue8reonvnr98n",
		grievanceId: "12ioi1rue8reonvnr98n",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Open",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Ronald Dosunmu",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi12iywrhy7rwuywurnn",
		grievanceId: "12ioi12iywrhy7rwuywurnn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Ronald Dosunmu",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi98wrun8fu98wwvrrev1nn",
		grievanceId: "12ioi98wrun8fu98wwvrrev1nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Ronald Dosunmu",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12i98ewnry89yf9rn8n21nn",
		grievanceId: "12i98ewnry89yf9rn8n21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Ronald Dosunmu",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12iofwrn98fnrh9ynh9n21nn",
		grievanceId: "12iofwrn98fnrh9ynh9n21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Adetunji Adeyinka",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioure89nu9frnh9wn91nn",
		grievanceId: "12ioure89nu9frnh9wn91nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Adetunji Adeyinka",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12iowifrnhuifwhifwhfn8rhw21nn",
		grievanceId: "12iowifrnhuifwhifwhfn8rhw21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Adetunji Adeyinka",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1iuwhrfnyw8wy21nn",
		grievanceId: "12ioi1iuwhrfnyw8wy21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Adetunji Adeyinka",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1wrmf9rnu8wnfh21nn",
		grievanceId: "12ioi1wrmf9rnu8wnfh21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Adetunji Adeyinka",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12iowhfnwnf8f1n2in21nn",
		grievanceId: "12iowhfnwnf8f1n2in21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1frhwnhwnfn21nn",
		grievanceId: "12ioi1frhwnhwnfn21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Closed",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12iowerwofonyeru2in21nn",
		grievanceId: "12iowerwofonyeru2in21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12iofqfwy98wfin21nn",
		grievanceId: "12iofqfwy98wfin21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12iof3ih3498f9h9n21nn",
		grievanceId: "12iof3ih3498f9h9n21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Voke Onoriode",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1f3iy398y49fh39u21nn",
		grievanceId: "12ioi1f3iy398y49fh39u21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Toni Odujinrin",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1f4hf8fuu4f8921nn",
		grievanceId: "12ioi1f4hf8fuu4f8921nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Toni Odujinrin",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi134ifuh3498yf983yf1nn",
		grievanceId: "12ioi134ifuh3498yf983yf1nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Toni Odujinrin",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1f4ih43fhy4f3n21nn",
		grievanceId: "12ioi1f4ih43fhy4f3n21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Toni Odujinrin",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi12i34hg8f9jf39nn",
		grievanceId: "12ioi12i34hg8f9jf39nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Toni Odujinrin",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi12894893u934tnn",
		grievanceId: "12ioi12894893u934tnn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Toni Odujinrin",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi12io1n2eojwe099uwe90few",
		grievanceId: "12ioi12io1n2eojwe099uwe90few",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Chambers",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi1weiiewjojew09n21nn",
		grievanceId: "12ioi1weiiewjojew09n21nn",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Resolved",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Chambers",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi12io1newwelwepfwe",
		grievanceId: "12ioi12io1newwelwepfwe",
		title: "whine joy",
		description: "as of now iam a distributor of pine tm from vizag andhra pradesh as of **** oct all our costumer bills got reversed and my money lost no responce from them as nearly ****/- lost because of them now there is no website of them...",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Pending",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Darel Chambers",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
	{
		id: "12ioi12io1ewfknewono",
		grievanceId: "12ioi12io1ewfknewono",
		title: "An online vendor with insta handle @greggry.stores scammed me of #250,000 for intended for a weavon i never got",
		description: "tester nom",
		date: "2022-10-14",
		socialMediaHandle: "Twitter: @indaboski",
		status: "Pending",
		productCategory: "Footwares",
		resolutionWanted: {
			refund: true,
			compensation: true,
			apology: true,
			replacement: true,
		},
		companyName: "Kate Chambers",
		amountLost: "5000",
		transactionLocation: "Instagram",
	},
];
export default ComplaintData;
