const UserData = [
	{
		profilePic: "/Images/profilePic.png",
		userName: "Darrel Stewart",
		userEmail: "darelstewart@gmail.com",
		registrationDate: "December 20,2021",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Darrel Stewart",
		userEmail: "darelstewart@gmail.com",
		registrationDate: "December 20,2021",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Darrel Stewart",
		userEmail: "darelstewart@gmail.com",
		registrationDate: "December 20,2021",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Voke Onoriode",
		userEmail: "voke_onoriode@yahoo.com",
		registrationDate: "July 21,2016",
		userPhone: "09033993399",
		status: "Verified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Voke Onoriode",
		userEmail: "voke_onoriode@yahoo.com",
		registrationDate: "July 21,2016",
		userPhone: "09033993399",
		status: "Verified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Voke Onoriode",
		userEmail: "voke_onoriode@yahoo.com",
		registrationDate: "July 21,2016",
		userPhone: "09033993399",
		status: "Verified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Voke Onoriode",
		userEmail: "voke_onoriode@yahoo.com",
		registrationDate: "July 21,2016",
		userPhone: "09033993399",
		status: "Verified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Voke Onoriode",
		userEmail: "voke_onoriode@yahoo.com",
		registrationDate: "July 21,2016",
		userPhone: "09033993399",
		status: "Verified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Dele Adeboye",
		userEmail: "dele_adeboye@yahoo.com",
		registrationDate: "November 1,2018",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Dele Adeboye",
		userEmail: "dele_adeboye@yahoo.com",
		registrationDate: "November 1,2018",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Dele Adeboye",
		userEmail: "dele_adeboye@yahoo.com",
		registrationDate: "November 1,2018",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Dele Adeboye",
		userEmail: "dele_adeboye@yahoo.com",
		registrationDate: "November 1,2018",
		userPhone: "09033993399",
		status: "Unverified",
	},
	{
		profilePic: "/Images/profilePic.png",
		userName: "Dele Adeboye",
		userEmail: "dele_adeboye@yahoo.com",
		registrationDate: "November 1,2018",
		userPhone: "09033993399",
		status: "Unverified",
	},
];

export default UserData;
